# Generated by Django 4.2.2 on 2023-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField(default=10)),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('useage', models.TextField(default='')),
                ('category', models.CharField(choices=[('ms', 'Men Shoes'), ('ws', 'Women Shoes'), ('el', 'Electronics'), ('cl', 'Clothings'), ('ph', 'Phones'), ('fs', 'Foodstuff'), ('cs', 'Cosmetic'), ('am', 'Auto mobile')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
